Repository OptimistikSAS/OIBus, pull requests merged in 2023-09, with the labels that each got.

#2793 feat(opchda): Add overlap settings in ms
  src/south/south-opchda/south-opchda.js
  src/south/south-opchda/south-opchda.schema.jsx
  src/south/south-opchda/south-opchda.spec.js
Labels: feature:south

#2795 chore(oibus-v2): release 2.10.0
  .github/release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2804 chore(main): release 3.0.1
  .github/release-please-manifest.json
  CHANGELOG.md
  backend/package-lock.json
  backend/package.json
  documentation/package-lock.json
  documentation/package.json
  frontend/package-lock.json
  frontend/package.json
  shared/package-lock.json
  shared/package.json
Labels: autorelease: pending

#2814 oia-test
  backend/src/index.ts
  backend/src/north/north-oianalytics/north-oianalytics.spec.ts
  backend/src/north/north-oianalytics/north-oianalytics.ts
  backend/src/service/oibus.service.spec.ts
  backend/src/service/oibus.service.ts
  backend/src/service/utils.spec.ts
  backend/src/service/utils.ts
  backend/src/south/south-oianalytics/south-oianalytics.spec.ts
  backend/src/south/south-oianalytics/south-oianalytics.ts
  backend/src/web-server/controllers/oibus.controller.spec.ts
  backend/src/web-server/controllers/oibus.controller.ts
Labels: bug

#2815 proxy-fix-user
  backend/src/service/proxy.service.spec.ts
  backend/src/service/proxy.service.ts
Labels: bug

#2817 status-display
  frontend/src/app/history-query/history-query-list.component.html
  frontend/src/app/history-query/history-query-list.component.spec.ts
  frontend/src/app/north/north-list.component.html
  frontend/src/app/north/north-list.component.spec.ts
  frontend/src/app/north/north-list.component.ts
  frontend/src/app/south/south-list.component.html
  frontend/src/app/south/south-list.component.spec.ts
  frontend/src/app/south/south-list.component.ts
  frontend/src/i18n/en.json
Labels: feature:web-client

#2818 fix-connector-metrics
  backend/src/north/north-connector.ts
  backend/src/repository/north-connector-metrics.repository.spec.ts
  backend/src/repository/north-connector-metrics.repository.ts
  backend/src/repository/south-connector-metrics.repository.spec.ts
  backend/src/repository/south-connector-metrics.repository.ts
  backend/src/service/north-connector-metrics.service.spec.ts
  backend/src/service/south-connector-metrics.service.spec.ts
  frontend/src/app/history-query/history-query-detail/history-metrics/history-metrics.component.html
  frontend/src/app/north/north-metrics/north-metrics.component.html
  frontend/src/app/north/north-metrics/north-metrics.component.spec.ts
  frontend/src/app/south/south-metrics/south-metrics.component.html
  frontend/src/app/south/south-metrics/south-metrics.component.spec.ts
  frontend/src/i18n/en.json
  shared/model/engine.model.ts
Labels: bug, feature:south, feature:north, feature:history-query

#2816 chore(main): release 3.0.2
  .github/release-please-manifest.json
  CHANGELOG.md
  backend/package-lock.json
  backend/package.json
  documentation/package-lock.json
  documentation/package.json
  frontend/package-lock.json
  frontend/package.json
  shared/package-lock.json
  shared/package.json
Labels: autorelease: pending

#2826 south-items-export-import
  backend/src/tests/__mocks__/south-service.mock.ts
  backend/src/web-server/controllers/south-connector.controller.spec.ts
  backend/src/web-server/controllers/south-connector.controller.ts
  backend/src/web-server/routes/index.ts
  frontend/src/app/services/south-connector.service.spec.ts
  frontend/src/app/services/south-connector.service.ts
  frontend/src/app/south/edit-south/edit-south.component.html
  frontend/src/app/south/import-south-items-modal/import-south-items-modal.component.html
  frontend/src/app/south/import-south-items-modal/import-south-items-modal.component.scss
  frontend/src/app/south/import-south-items-modal/import-south-items-modal.component.spec.ts
  frontend/src/app/south/import-south-items-modal/import-south-items-modal.component.ts
  frontend/src/app/south/south-detail/south-detail.component.html
  frontend/src/app/south/south-detail/south-detail.component.ts
  frontend/src/app/south/south-items/south-items.component.html
  frontend/src/app/south/south-items/south-items.component.spec.ts
  frontend/src/app/south/south-items/south-items.component.ts
  frontend/src/i18n/en.json
Labels: bug, feature:south
