Repository OptimistikSAS/OIBus, pull requests merged in 2024-03, with the labels that each got.

#3286 feat(logger): Add OIAnalytics Pino transport and refactor registration service to reload logger on change
  backend/package-lock.json
  backend/package.json
  backend/src/db/entity-migrations/v3.2.0-oia-registration.ts
  backend/src/index.ts
  backend/src/repository/engine.repository.spec.ts
  backend/src/repository/engine.repository.ts
  backend/src/repository/log.repository.spec.ts
  backend/src/service/logger/logger.service.spec.ts
  backend/src/service/logger/logger.service.ts
  backend/src/service/logger/loki-transport.ts
  backend/src/service/logger/oianalytics-transport.ts
  backend/src/service/oia/command.service.spec.ts
  backend/src/service/oia/command.service.ts
  backend/src/service/oia/registration.service.spec.ts
  backend/src/service/oia/registration.service.ts
  backend/src/service/oibus.service.spec.ts
  backend/src/service/oibus.service.ts
  backend/src/service/reload.service.spec.ts
  backend/src/service/reload.service.ts
  backend/src/tests/__mocks__/koa-context.mock.ts
  backend/src/tests/__mocks__/oibus-service.mock.ts
  backend/src/tests/__mocks__/registration-service.mock.ts
  backend/src/tests/__mocks__/reload-service.mock.ts
  backend/src/web-server/controllers/registration.controller.spec.ts
  backend/src/web-server/controllers/registration.controller.ts
  backend/src/web-server/controllers/validators/engine.validator.spec.ts
  backend/src/web-server/controllers/validators/oibus-validation-schema.ts
  backend/src/web-server/koa.ts
  backend/src/web-server/middlewares/oibus.ts
  backend/src/web-server/web-server.ts
  backend/tsconfig.app.json
  frontend/src/app/engine/edit-engine/edit-engine.component.html
  frontend/src/app/engine/edit-engine/edit-engine.component.spec.ts
  frontend/src/app/engine/edit-engine/edit-engine.component.ts
  frontend/src/app/engine/engine-detail.component.html
  frontend/src/app/engine/engine-detail.component.spec.ts
  frontend/src/i18n/en.json
  shared/model/engine.model.ts
  shared/model/logs.model.ts
Labels: enhancement, feature:logs

#3290 fix: Add error interceptor to display HTTP error in a notification
  frontend/src/app/shared/error-interceptor.service.spec.ts
  frontend/src/app/shared/error-interceptor.service.ts
  frontend/src/i18n/en.json
  frontend/src/main.ts
Labels: bug, feature:web-client

#3308 fix(web-server): fix IP filter reloading on change
  backend/src/index.ts
  backend/src/tests/__mocks__/proxy-server.mock.ts
  backend/src/tests/__mocks__/reload-service.mock.ts
  backend/src/web-server/controllers/ip-filter.controller.ts
  backend/src/web-server/middlewares/oibus.ts
  backend/src/web-server/proxy-server.ts
  backend/src/web-server/web-server.ts
Labels: bug, feature:engine

#3238 chore(main): release 3.2.0
  .github/release-please-manifest.json
  CHANGELOG.md
  backend/package-lock.json
  backend/package.json
  documentation/package-lock.json
  documentation/package.json
  frontend/package-lock.json
  frontend/package.json
  launcher/package-lock.json
  launcher/package.json
  shared/package-lock.json
  shared/package.json
Labels: autorelease: pending

#3328 chore(main): release 3.2.0
  .github/release-please-manifest.json
  CHANGELOG.md
  backend/package-lock.json
  backend/package.json
  documentation/package-lock.json
  documentation/package.json
  frontend/package-lock.json
  frontend/package.json
  launcher/package-lock.json
  launcher/package.json
  shared/package-lock.json
  shared/package.json
Labels: autorelease: pending

#3332 chore(stable): release 3.2.0
  .github/release-please-manifest.json
  CHANGELOG.md
  backend/package-lock.json
  backend/package.json
  documentation/package-lock.json
  documentation/package.json
  frontend/package-lock.json
  frontend/package.json
  launcher/package-lock.json
  launcher/package.json
  shared/package-lock.json
  shared/package.json
Labels: autorelease: pending
