Repository OptimistikSAS/OIBus, pull requests merged in 2024-04, with the labels that each got.

#3352 fix(oracle): Manage thick / thin mode oracle client
  backend/package-lock.json
  backend/package.json
  backend/src/db/entity-migrations/v3.2.1-oracle-thick-mode.ts
  backend/src/south/south-oracle/manifest.ts
  backend/src/south/south-oracle/south-oracle-no-lib.spec.ts
  backend/src/south/south-oracle/south-oracle.spec.ts
  backend/src/south/south-oracle/south-oracle.ts
  shared/model/south-settings.model.ts
Labels: bug, south

#3375 chore(stable): release 3.3.0
  .github/release-please-manifest.json
  CHANGELOG.md
  backend/package-lock.json
  backend/package.json
  documentation/package-lock.json
  documentation/package.json
  frontend/package-lock.json
  frontend/package.json
  launcher/package-lock.json
  launcher/package.json
  shared/package-lock.json
  shared/package.json
Labels: autorelease: pending

#3379 fix-migration-oia-3.2
  backend/src/db/entity-migrations/v3.2.0-oia-registration.ts
Labels: bug

#3381 fix: fix OIAnalytics registration url and accept unauthorized
  backend/src/db/entity-migrations/v3.3.1-oia-registration.ts
  backend/src/service/oia/registration.service.spec.ts
  backend/src/service/oia/registration.service.ts
Labels: bug

#3382 export-import-fix
  backend/src/web-server/controllers/history-query.controller.spec.ts
  backend/src/web-server/controllers/history-query.controller.ts
  backend/src/web-server/controllers/south-connector.controller.spec.ts
  backend/src/web-server/controllers/south-connector.controller.ts
  backend/src/web-server/controllers/validators/joi.validator.ts
Labels: bug

#3383 docs-migrate
  documentation/docs/guide/installation/migrate.mdx
Labels: documentation

#3380 chore(stable): release 3.3.1
  .github/release-please-manifest.json
  CHANGELOG.md
  backend/package-lock.json
  backend/package.json
  documentation/package-lock.json
  documentation/package.json
  frontend/package-lock.json
  frontend/package.json
  launcher/package-lock.json
  launcher/package.json
  shared/package-lock.json
  shared/package.json
Labels: autorelease: pending

#3390 duplicate-items
  frontend/src/app/history-query/edit-history-query/edit-history-query.component.html
  frontend/src/app/history-query/history-query-items/history-query-items.component.ts
  frontend/src/app/south/south-items/south-items.component.ts
Labels: bug

#3392 duplicate-secrets
  backend/src/web-server/controllers/history-query.controller.spec.ts
  backend/src/web-server/controllers/history-query.controller.ts
  backend/src/web-server/controllers/north-connector.controller.spec.ts
  backend/src/web-server/controllers/north-connector.controller.ts
  backend/src/web-server/controllers/south-connector.controller.spec.ts
  backend/src/web-server/controllers/south-connector.controller.ts
  frontend/src/app/history-query/edit-history-query/edit-history-query.component.ts
  frontend/src/app/north/edit-north/edit-north.component.ts
  frontend/src/app/services/history-query.service.spec.ts
  frontend/src/app/services/history-query.service.ts
  frontend/src/app/services/north-connector.service.spec.ts
  frontend/src/app/services/north-connector.service.ts
  frontend/src/app/services/south-connector.service.spec.ts
  frontend/src/app/services/south-connector.service.ts
  frontend/src/app/south/edit-south/edit-south.component.ts
Labels: bug

#3391 chore(stable): release 3.3.2
  .github/release-please-manifest.json
  CHANGELOG.md
  backend/package-lock.json
  backend/package.json
  documentation/package-lock.json
  documentation/package.json
  frontend/package-lock.json
  frontend/package.json
  launcher/package-lock.json
  launcher/package.json
  shared/package-lock.json
  shared/package.json
Labels: autorelease: pending
