Repository OptimistikSAS/OIBus, pull requests merged in 2025-06, with the labels that each got.

#3971 chore(stable): release 3.6.0
  .github/release-please-manifest.json
  CHANGELOG.md
  backend/package-lock.json
  backend/package.json
  documentation/package-lock.json
  documentation/package.json
  frontend/package-lock.json
  frontend/package.json
  launcher/package-lock.json
  launcher/package.json
Labels: autorelease: pending

#3977 fix(opcua): fix null value log for opcua south connector
  backend/src/south/south-opcua/south-opcua.spec.ts
  backend/src/south/south-opcua/south-opcua.ts
Labels: south

#4000 fix(api): properly manage file received from add-content endpoint
  backend/src/web-server/controllers/content.controller.ts
Labels: engine
