Repository OptimistikSAS/OIBus, pull requests merged in 2025-08, with the labels that each got.

#4059 fix(proxy-server): fix ip filtering in proxy server and port forwarding
  backend/src/web-server/proxy-server.spec.ts
  backend/src/web-server/proxy-server.ts
Labels: engine

#4063 fix(oianalytics): fix command acknowledgment if not found
  backend/src/service/oia/oianalytics-command.service.spec.ts
  backend/src/service/oia/oianalytics-command.service.ts
Labels: oianalytics

#4081 fix(engine): add OIBus user agent in HTTP Request utils
  backend/src/service/http-request.utils.spec.ts
  backend/src/service/http-request.utils.ts
Labels: engine

#4080 chore(stable): release 3.6.7
  .github/release-please-manifest.json
  CHANGELOG.md
  backend/package-lock.json
  backend/package.json
  documentation/package-lock.json
  documentation/package.json
  frontend/package-lock.json
  frontend/package.json
  launcher/package-lock.json
  launcher/package.json
Labels: autorelease: pending
