Repository OptimistikSAS/OIBus, pull requests merged in 2025-10, with the labels that each got.

#4122 fix(azure): fix migration of azure north connector in 3.5.0
  backend/src/migration/entity-migrations/v3.5.0.ts
Labels: north

#4125 chore: update NodeJS to v24
  .nvmrc
  backend/package-lock.json
  backend/package.json
  documentation/package-lock.json
  documentation/package.json
  frontend/package-lock.json
  frontend/package.json
  launcher/package-lock.json
  launcher/package.json
Labels: dependencies, dev issue

#4127 fix(history): properly manage item testing when creating history from south
  backend/src/web-server/controllers/history-query.controller.spec.ts
  backend/src/web-server/controllers/history-query.controller.ts
  frontend/src/app/history-query/edit-history-query/edit-history-query.component.html
  frontend/src/app/history-query/history-query-items/edit-history-query-item-modal/edit-history-query-item-modal.component.html
  frontend/src/app/history-query/history-query-items/edit-history-query-item-modal/edit-history-query-item-modal.component.spec.ts
  frontend/src/app/history-query/history-query-items/edit-history-query-item-modal/edit-history-query-item-modal.component.ts
  frontend/src/app/history-query/history-query-items/history-query-items.component.ts
  frontend/src/app/services/history-query.service.ts
  frontend/src/app/south/south-items/south-item-test/south-item-test.component.spec.ts
  frontend/src/app/south/south-items/south-item-test/south-item-test.component.ts
Labels: history-query

#4129 fix(north): debug log instead of warning when task is already running
  backend/src/north/north-connector.spec.ts
  backend/src/north/north-connector.ts
  backend/src/service/logger/oianalytics-transport.ts
Labels: north, logs

#4112 chore(stable): release 3.6.9
  .github/release-please-manifest.json
  CHANGELOG.md
  backend/package-lock.json
  backend/package.json
  documentation/package-lock.json
  documentation/package.json
  frontend/package-lock.json
  frontend/package.json
  launcher/package-lock.json
  launcher/package.json
Labels: autorelease: pending
