Repository OptimistikSAS/OIBus, pull requests merged in 2025-01, with the labels that each got.

#3773 fix(north): do not create an empty folder on north connection test
  backend/src/service/cache/file-cache.service.ts
Labels: bug, north

#3774 feat(service): split controller, service and repository for certificate, user and log
  backend/shared/model/logs.model.ts
  backend/shared/model/user.model.ts
  backend/src/index.ts
  backend/src/repository/config/config-database.spec.ts
  backend/src/repository/config/user.repository.ts
  backend/src/service/certificate.service.spec.ts
  backend/src/service/certificate.service.ts
  backend/src/service/log.service.spec.ts
  backend/src/service/log.service.ts
  backend/src/service/logger/oianalytics-transport.ts
  backend/src/service/user.service.spec.ts
  backend/src/service/user.service.ts
  backend/src/tests/__mocks__/koa-context.mock.ts
  backend/src/tests/__mocks__/service/certificate-service.mock.ts
  backend/src/tests/__mocks__/service/log-service.mock.ts
  backend/src/tests/__mocks__/service/user-service.mock.ts
  backend/src/tests/utils/test-data.ts
  backend/src/web-server/controllers/certificate.controller.spec.ts
  backend/src/web-server/controllers/certificate.controller.ts
  backend/src/web-server/controllers/log.controller.spec.ts
  backend/src/web-server/controllers/log.controller.ts
  backend/src/web-server/controllers/user.controller.spec.ts
  backend/src/web-server/controllers/user.controller.ts
  backend/src/web-server/controllers/validators/oibus-validation-schema.ts
  backend/src/web-server/koa.ts
  backend/src/web-server/middlewares/auth.ts
  backend/src/web-server/middlewares/oibus.ts
  backend/src/web-server/routes/index.ts
  backend/src/web-server/web-server.ts
  frontend/src/app/app.component.spec.ts
  frontend/src/app/app.component.ts
  frontend/src/app/logs/logs.component.spec.ts
  frontend/src/app/navbar/navbar.component.spec.ts
  frontend/src/app/navbar/navbar.component.ts
  frontend/src/app/services/log.service.spec.ts
  frontend/src/app/services/user-settings.service.spec.ts
  frontend/src/app/services/user-settings.service.ts
  frontend/src/app/shared/current-user-testing.ts
  frontend/src/app/shared/current-user.service.ts
  frontend/src/app/user-settings/change-password-modal/change-password-modal.component.spec.ts
  frontend/src/app/user-settings/edit-user-settings/edit-user-settings.component.spec.ts
  frontend/src/app/user-settings/edit-user-settings/edit-user-settings.component.ts
Labels: enhancement, dev issue

#3778 chore: fix settings interface generator
  backend/shared/model/south-settings.model.ts
  backend/src/settings-interface.generator.ts
  backend/src/south/south-opcua/south-opcua.spec.ts
  backend/src/south/south-opcua/south-opcua.ts
Labels: bug

#3779 chore(stable): release 3.5.0
  .github/release-please-manifest.json
  CHANGELOG.md
  backend/package-lock.json
  backend/package.json
  documentation/package-lock.json
  documentation/package.json
  frontend/package-lock.json
  frontend/package.json
  launcher/package-lock.json
  launcher/package.json
Labels: autorelease: pending

#3781 fix(migration): properly remove north oibus connectors
  backend/src/migration/entity-migrations/v3.5.0.ts
Labels: bug

#3788 chore(stable): release 3.5.2
  .github/release-please-manifest.json
  CHANGELOG.md
  backend/package-lock.json
  backend/package.json
  documentation/package-lock.json
  documentation/package.json
  frontend/package-lock.json
  frontend/package.json
  launcher/package-lock.json
  launcher/package.json
Labels: autorelease: pending

#3792 fix(south): do not create tmp file if testing south connector
  backend/src/south/south-connector.spec.ts
  backend/src/south/south-connector.ts
  backend/src/south/south-folder-scanner/south-folder-scanner.spec.ts
  backend/src/south/south-folder-scanner/south-folder-scanner.ts
  backend/src/south/south-mssql/south-mssql.ts
  backend/src/south/south-mysql/south-mysql.ts
  backend/src/south/south-odbc/south-odbc.ts
  backend/src/south/south-oianalytics/south-oianalytics.ts
  backend/src/south/south-oledb/south-oledb.ts
  backend/src/south/south-opc/south-opc.ts
  backend/src/south/south-oracle/south-oracle.ts
  backend/src/south/south-postgresql/south-postgresql.ts
  backend/src/south/south-sftp/south-sftp.spec.ts
  backend/src/south/south-sftp/south-sftp.ts
  backend/src/south/south-slims/south-slims.ts
  backend/src/south/south-sqlite/south-sqlite.ts
Labels: bug

#3793 chore(stable): release 3.5.3
  .github/release-please-manifest.json
  CHANGELOG.md
  backend/package-lock.json
  backend/package.json
  documentation/package-lock.json
  documentation/package.json
  frontend/package-lock.json
  frontend/package.json
  launcher/package-lock.json
  launcher/package.json
Labels: autorelease: pending

#3795 chore(stable): release 3.5.4
  .github/release-please-manifest.json
  CHANGELOG.md
  backend/package-lock.json
  backend/package.json
  documentation/package-lock.json
  documentation/package.json
  frontend/package-lock.json
  frontend/package.json
  launcher/package-lock.json
  launcher/package.json
Labels: autorelease: pending

#3801 fix(proxy-server): log error if port is already used
  backend/src/web-server/proxy-server.spec.ts
  backend/src/web-server/proxy-server.ts
Labels: bug

#3802 fix(history-query): properly manage south items when creating from south
  backend/src/service/history-query.service.ts
  frontend/src/app/history-query/edit-history-query/edit-history-query.component.spec.ts
  frontend/src/app/history-query/edit-history-query/edit-history-query.component.ts
  frontend/src/app/history-query/history-query-items/history-query-items.component.ts
Labels: bug, history-query

#3804 feat(oianalytics): retrieve commands for ip filters and certificates
  backend/shared/model/command.model.ts
  backend/src/index.ts
  backend/src/migration/entity-migrations/v3.5.4-oianalytics-message-and-commands.ts
  backend/src/model/oianalytics-command.model.ts
  backend/src/repository/config/config-database.spec.ts
  backend/src/repository/config/oianalytics-command.repository.ts
  backend/src/service/certificate.service.spec.ts
  backend/src/service/certificate.service.ts
  backend/src/service/ip-filter.service.spec.ts
  backend/src/service/ip-filter.service.ts
  backend/src/service/oia/oianalytics-command.service.spec.ts
  backend/src/service/oia/oianalytics-command.service.ts
  backend/src/service/oia/oianalytics.model.ts
  backend/src/service/oibus.service.spec.ts
  backend/src/service/oibus.service.ts
  backend/src/tests/__mocks__/koa-context.mock.ts
  backend/src/tests/__mocks__/service/ip-filter-service.mock.ts
  backend/src/web-server/controllers/ip-filter.controller.spec.ts
  backend/src/web-server/controllers/ip-filter.controller.ts
  backend/src/web-server/koa.ts
  backend/src/web-server/middlewares/ip-filter.ts
  backend/src/web-server/web-server.ts
  frontend/src/app/engine/oia-module/register-oibus-modal/register-oibus-modal.component.html
  frontend/src/app/shared/oibus-command-type-enum.pipe.spec.ts
  frontend/src/i18n/en.json
Labels: enhancement, oianalytics

#3806 chore(stable): release 3.5.5
  .github/release-please-manifest.json
  CHANGELOG.md
  backend/package-lock.json
  backend/package.json
  documentation/package-lock.json
  documentation/package.json
  frontend/package-lock.json
  frontend/package.json
  launcher/package-lock.json
  launcher/package.json
Labels: autorelease: pending

#3814 chore(stable): release 3.5.6
  .github/release-please-manifest.json
  CHANGELOG.md
  backend/package-lock.json
  backend/package.json
  documentation/package-lock.json
  documentation/package.json
  frontend/package-lock.json
  frontend/package.json
  launcher/package-lock.json
  launcher/package.json
Labels: autorelease: pending

#3816 chore(stable): release 3.5.7
  .github/release-please-manifest.json
  CHANGELOG.md
  backend/package-lock.json
  backend/package.json
  documentation/package-lock.json
  documentation/package.json
  frontend/package-lock.json
  frontend/package.json
  launcher/package-lock.json
  launcher/package.json
Labels: autorelease: pending

#3819 fix(oianalytics): only ignore remote update command if flag is set to true
  backend/src/service/oia/oianalytics-command.service.spec.ts
  backend/src/service/oia/oianalytics-command.service.ts
Labels: bug

#3820 chore(stable): release 3.5.8
  .github/release-please-manifest.json
  CHANGELOG.md
  backend/package-lock.json
  backend/package.json
  documentation/package-lock.json
  documentation/package.json
  frontend/package-lock.json
  frontend/package.json
  launcher/package-lock.json
  launcher/package.json
Labels: autorelease: pending

#3822 ci: fix doc links and windows setup release
  .github/workflows/build.yml
  build/deps/win-x64/setup.iss
  documentation/docs/guide/installation/_macos.mdx
  documentation/docs/guide/installation/_windows.mdx
  documentation/i18n/zh/docusaurus-plugin-content-docs/current/guide/installation/macos.mdx
  documentation/i18n/zh/docusaurus-plugin-content-docs/current/guide/installation/windows.mdx
Labels: bug, ci
